### ISSUE TITLE
`안내별`의 효과가 Description에 모두 적혀있지 않음

### ISSUE THREAD

**Issue by tykr0001** [scarf005/Marisa#132]
### Language

Korean

### Summary

Label을 Bug로 달지 Localization으로 달지 조금 고민했음. 둘 다 조금씩 문제가 있다.

---

### BUG
먼저 `안내별(GuidingStar)`은 원래 카드 보상 풀에는 안들어가있으나 `스타더스트 래버리(StarDustReverie)` 나 `열린 우주(OpenUniverse)` 처럼 무작위 마리사 카드를 얻는 카드를 사용 시 1/100 확률로 나옴.(https://github.com/scarf005/Marisa/tree/main/src/main/kotlin/marisa/MarisaContinued.kt 의 randomMarisaCard)

아래는 원작자가 본래의 무작위 카드 생성 풀에 들어가있지도 않은 안내별을 왜 굳이 1/100 확률로 튀어나오게 만들었는가에 대한 추측임
1. 사실 예전 마리사 모드에는 사용 시 `안내별`을 덱에 집어넣는 효과를 가진 `Polaris Unique`라는 카드가 있었다. (eng localization 파일에 그 흔적이 남아있음)
2. 따라서 derivations 에도 안내별이 들어가 있음.
3. 다른 무작위 생성 카드(위에서 나열한)에서 `안내별`이 아예 안나오게 만들지는 않으면서도 너무 빈번하게 튀어나오는 것을 인위적으로 조절하려고 메소드를 따로 만듦.
4. `Polaris Unique` 카드를 없애면서 관련 코드를 지웠으나 randomMarisaCard를 깜빡해 여전히 1/100 확률로 튀어나옴.

**일단 내 생각엔 `안내별`이 이제는 무작위 카드 생성으로 안나오는게 맞는 것 같음.**

---

### Localization
먼저 localization 파일은 디스크립션이 아래처럼 돼있음. 영어 버전도 동일하니 다른 모든 언어도 그럴 듯
```json
"GuidingStar": {
    "NAME": "안내별",
    "DESCRIPTION": "보존. NL 턴이 시작할 때 이 카드가 손에 있으면 [E] 를 얻습니다."
  },
```

근데 코드 보면 알겠지만 사실 안내별은 사용하면 소멸하고 새로운 안내별을 덱에 집어넣은 후, 버려진 카드 더미를 통째로 덱으로 퍼올리고나서 덱을 섞는 효과까지 포함되어 있음. 안내별이 무작위 카드 생성으로 나오는게 맞는 현상이면 디스크립션을 수정해야 할 듯.

### Are you interested in fixing this issue?

- [ ] I am willing to PR a fix for this issue.

**Comment by scarf005** [comment]
무작위로 나오지 않도록 수정하겠음
원작자 의도도 `polarisunique` 제거하면서 무작위 생성도 같이 지우는 거였을 것 같음
