### ISSUE TITLE
The upgraded card "Blaze Away+" consume energy with the second attack.

### ISSUE THREAD

**Issue by b510858** [scarf005/Marisa#152]
### How to reproduce

Started single player with the mod loader and the mod "Together with Spire".
Cast any card that needed energy, "Warning Up" is the best to show this bug.
Upgrade Blaze Away.
Use "Warning Up", leave you one energy.
Use "Blaze Away+", "Warning Up" is played once, then The chatacter say not enough energy and refuse to play "Warning Up" again.

Another show case is 1 cost card like "Simple Spark".
Use "Simple Spark", use one energy.
Use "Blaze Away", "Simple Spark" is played once, one energy consumed by "Blaze Away", no energy consumed by "Simple Spark", two energy in total.

Use "Simple Spark", use one energy.
Use "Blaze Away", "Simple Spark" is played twice, one energy consumed by "Blaze Away", one energy consumed by "Simple Spark", three energy in total.

It shows that the second attack played by "Blaze Away+" consume energy while the first attack do not.

**Comment by scarf005** [comment]
thank you for the report! could you please try without together with spire mod and check if the issue still persists?

**Comment by b510858** [comment]
Yes, the issue still persists without together with spire. It seems like the cost of first card is setted to 0 while the second one do not. The cost on the first card is green zero while the second one is white 1 or 2.
