### ISSUE TITLE
amplified oort cloud+ card gain only 3 plated armor(=amplifying bonus).

### ISSUE THREAD

**Issue by NNECT** [scarf005/Marisa#165]
### How to reproduce

I should gain plated armor 8 when using an amplified oort cloud+ card.
However, I only gain 3 (Amplifying bonus).

I have not tested the basic oort cloud card to see if it has the same issue.

I'm not good at English, Sorry.

**Comment by scarf005** [comment]
> hello @NNECT, the bug was fixed in #161 and released in [v3.0.2](https://github.com/scarf005/Marisa/releases/tag/v3.0.2). could you restart the game and check if its version is v3.0.2?

안녕하세요, 말씀하신 버그를 패치 #161 을 통해 수정했습니다. 게임 실행 후 [v3.0.2](https://github.com/scarf005/Marisa/releases/tag/v3.0.2)인지 확인해주시겠어요?

**Comment by NNECT** [comment]
> > hello @NNECT, the bug was fixed in #161 and released in [v3.0.2](https://github.com/scarf005/Marisa/releases/tag/v3.0.2). could you restart the game and check if its version is v3.0.2?
> 
> 안녕하세요, 말씀하신 버그를 패치 #161 을 통해 수정했습니다. 게임 실행 후 [v3.0.2](https://github.com/scarf005/Marisa/releases/tag/v3.0.2)인지 확인해주시겠어요?

안녕하세요.
확인해보니 v2.0.2였습니다...
어째선지 모드가 자동 업데이트가 안 되고 있었네요;;
빠른 답변 감사합니다.
수고하세요!

**Comment by scarf005** [comment]
확인 결과 새 기능 추가가 게임 전체에 영향을 주는 버그를 발생시켜 (#166) 우선은 버전 v2.0.2로 롤백시켰습니다. 불편을 드려 죄송합니다.
