### ISSUE TITLE
Translation to Japanese

### ISSUE THREAD

**Issue by IDBT** [scarf005/Marisa#175]
### Language

Japanese

### Summary

From the original mod, there were some errors in the Japanese translation and some bugs.

Some cards and items had no description of their effects in Japanese,
There were also some cards that were not translated, or whose effects were translated completely differently than they actually were.

As a Japanese speaker, I would like to help with the translation.

My first time using GitHub and my English is not very good, so can I be inconvenienced?
Translated with Deep.L

───────────────────────────────────────────
Original Documents:
元のMODから、日本語の翻訳のミスや、バグが存在していました。

日本語では、一部、効果の記載がないカードやアイテムがあったり、
翻訳がなされていないものや、効果が全く実際と異なった翻訳がなされたカードが有りました。

日本語話者として、翻訳に助力できればと思います。
GitHubを使用するのは初めてで、英語もおぼつかないのでご迷惑をおかけするかもしれませんが、
参加してもよいでしょうか。

### Are you interested in fixing this issue?

- [X] I am willing to PR a fix for this issue.

**Comment by scarf005** [comment]
Hello, thank you for deciding to help with the translation! I haven't wrote a guide for translation yet, but you could edit the localization file here: <https://github.com/scarf005/Marisa/tree/main/src/main/resources/localization/JPN>

---

> こんにちは、翻訳に協力することを決めてくれてありがとうございます！まだ翻訳の手引きは書いていませんが、ローカライズファイルはこちらで編集できますよ： <https://github.com/scarf005/Marisa/tree/main/src/main/resources/localization/JPN>
> (translated with deepl)
