### ISSUE TITLE
`Shooting Echo` returns to hand even when it did not exhaust `Burn`

### ISSUE THREAD

**Issue by IDBT** [scarf005/Marisa#197]
### How to reproduce

I have encountered a situation that I believe to be a bug and would like to report it.

- Conditions
1. Exhausted a "Burn" Status card by "Shooting Echo". It come back into hand.(this is true require, I think.)
2. After 1, hands are less than 2 (including "Shooting echo"). 
3. Use "Shooting Echo" without exhaust any card or with exhausting non-"Burn" card
4. "Shooting Echo" come back into hand.

The behavior from 3 to 4 seems to be a incorrect action that differ from the description of this card.
(This is because I thought that "Shooting Echo" would return to the hand only one time when the "Burn" was exhausted.)

Currently, when the cost of "Shooting Echo" is reduced to 0 by some way, it can continue to attack the opponent forever.

**Comment by scarf005** [comment]
I was unable to reproduce the issue. I tried following steps:

1. `hand discard all`
2. `hand add ShootingEcho`
3. attack any enemy with ShootingEcho.

but the card does not return from discard pile as intended.

![image](https://user-images.githubusercontent.com/54838975/232976641-a8e9dc6a-521d-4537-8bbb-af5318444482.png)

> To make reproducing bugs easier, please use basemod's [Console](https://alexdriedger.github.io/SlayTheSpireModding/docs/console) command, surrounded with backtick (`) for each steps. Screenshot or Videos are also welcome.

could you please follow the instruction in bug report form and update `How to reproduce`?

**Comment by IDBT** [comment]
I checked it again myself, and indeed I could not reproduce it with the procedure I originally presented.

However, it appears that if you perform the above procedure with the **"Shooting Echo" costing 0**, the card come back into hands unlimitedly.

I don't know how to use the console command, so sorry again for the text.
but will try to capture this video somehow.

**Comment by IDBT** [comment]
https://user-images.githubusercontent.com/119684780/232989662-72cdb88e-a650-4bff-b9cc-4f58b8381970.mp4

It goes like this.
Shooting Echo uses "Madness" to reduce the cost to zero, but a similar situation could also be achieved with "Mummy's Hand" in a relic.

**Comment by scarf005** [comment]
i was able to reproduce the issue using following commands:

https://user-images.githubusercontent.com/54838975/233089487-8417546c-24e3-4e4f-ace2-6d7fb35c6a4b.mp4

1. `hand discard all`
2. `hand add Burn`
3. `hand add Madness 3 2`
4. `hand add ShootingEcho 3`
5. `fight Transient`
6. use all Madness to reduce all the cost of Shooting Echo to 0
7. use a Shooting Echo and exhaust Burn
8. use a Shooting Echo and exhaust another Shooting Echo
9. the last Shooting Echo returns to hand infinitely

---

| `Mods` | `BaseMod` |
|--------|--------|
| ![image](https://user-images.githubusercontent.com/54838975/233089827-1382b9f7-74ea-4261-b020-0605964cc784.png) | ![Modded Slay the Spire_01](https://user-images.githubusercontent.com/54838975/233089870-e4f712dd-318c-4abc-9518-380cd448b206.png) | 

you can enable the console by:
1. visit `Mods` in the main menu
2. click `BaseMod`
3. click `Enable dev console` and `Enable Autocompletion`
4. open console using (`) key (the key below ESC key which also has ~)
