### ISSUE TITLE
incompatible with ussr mod

### ISSUE THREAD

**Issue by pphelper** [scarf005/Marisa#211]
### How to reproduce

cannot run game 

### Crash log

Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (12-18-2022)
 - ModTheSpire (3.30.3)
Mod list:
 - basemod (5.52.3)
 - stslib (2.10.0)
 - MarisaContinued (3.2.0)
 - sovietmod (1.2.8)

Begin patching...
Patching enums...Done.
Finding core patches...
Finding patches...
Patching Overrides...
Injecting patches...Done.
Compiling patched classes...Done.
Busting enums...Done.

Setting isModded = true...Done.

Adding ModTheSpire to version...Done.

Initializing mods...
 - BaseMod
   - basemod.BaseMod
libgdx version 1.9.5
13:40:02.261 INFO basemod.BaseMod> initializeGson
13:40:02.272 INFO basemod.BaseMod> initializeTypeMaps
13:40:02.273 INFO basemod.BaseMod> Registered MonsterStrings
13:40:02.274 INFO basemod.BaseMod> Registered PowerStrings
13:40:02.275 INFO basemod.BaseMod> Registered CardStrings
13:40:02.275 INFO basemod.BaseMod> Registered RelicStrings
13:40:02.275 INFO basemod.BaseMod> Registered EventStrings
13:40:02.276 INFO basemod.BaseMod> Registered PotionStrings
13:40:02.276 INFO basemod.BaseMod> Registered CreditStrings
13:40:02.277 INFO basemod.BaseMod> Registered TutorialStrings
13:40:02.278 INFO basemod.BaseMod> Registered KeywordStrings
13:40:02.278 INFO basemod.BaseMod> Registered ScoreBonusStrings
13:40:02.279 INFO basemod.BaseMod> Registered CharacterStrings
13:40:02.280 INFO basemod.BaseMod> Registered UIStrings
13:40:02.281 INFO basemod.BaseMod> Registered OrbStrings
13:40:02.281 INFO basemod.BaseMod> Registered StanceStrings
13:40:02.281 INFO basemod.BaseMod> Registered RunModStrings
13:40:02.283 INFO basemod.BaseMod> Registered BlightStrings
13:40:02.283 INFO basemod.BaseMod> Registered AchievementStrings
13:40:02.283 INFO basemod.BaseMod> initializePowerMap
13:40:02.649 INFO basemod.BaseMod> initializeUnderscorePowerIDs
   - 405ms
 - StSLib
   - com.evacipated.cardcrawl.mod.stslib.StSLib
   - 0ms
 - Marisa: Continued (霧雨 魔理沙)
   - marisa.MarisaContinued
13:40:02.716 INFO Marisa> creating the color : MARISA_COLOR
   - 54ms
 - theSovietUnion苏联ссср
   - ModExample.ModCore.SovietMod
   - 0ms
Done.

Starting game...
13:40:02.718 INFO desktop.DesktopLauncher> time: 1687614002717
13:40:02.718 INFO desktop.DesktopLauncher> version: 2022-12-18
13:40:02.718 INFO desktop.DesktopLauncher> libgdx:  1.9.5
13:40:02.718 INFO desktop.DesktopLauncher> default_locale: zh_CN
13:40:02.718 INFO desktop.DesktopLauncher> default_charset: GBK
13:40:02.718 INFO desktop.DesktopLauncher> default_encoding: GBK
13:40:02.718 INFO desktop.DesktopLauncher> java_version: 1.8.0_144
13:40:02.718 INFO desktop.DesktopLauncher> os_arch: amd64
13:40:02.719 INFO desktop.DesktopLauncher> os_name: Windows 10
13:40:02.719 INFO desktop.DesktopLauncher> os_version: 10.0
13:40:02.719 INFO core.SystemStats> MEMORY STATS:
Free Memory: 1,058Mb
Max Memory: 11,556Mb
Allocated Memory: 1,992Mb
Unallocated Memory: 9,564Mb
Total Free Memory: 10,622Mb
Used Memory: 933Mb

13:40:02.720 INFO core.SystemStats> DISK STATS:
Total Space: 1,596,373Mb
Usable Space: 1,064,841Mb
Free Space: 1,064,841Mb

13:40:02.722 INFO core.DisplayConfig> Reading info.displayconfig
13:40:02.724 INFO core.DisplayConfig> DisplayConfig successfully read.
13:40:02.724 INFO desktop.DesktopLauncher> [FULLSCREEN_MODE]
13:40:02.724 INFO desktop.DesktopLauncher> Running the game in: 3840 x 2160
13:40:02.725 INFO desktop.DesktopLauncher> Settings successfully loaded
13:40:02.725 INFO desktop.DesktopLauncher> Launching application...
13:40:02.990 INFO ststwitch.TwitchConfig> The 'twitchconfig.txt' already exists, not overwriting it.
13:40:02.991 INFO core.CardCrawlGame> DistributorPlatform=steam
13:40:02.991 INFO core.CardCrawlGame> isModded=true
13:40:02.991 INFO core.CardCrawlGame> isBeta=false
13:40:03.119 INFO steam.SteamIntegration> [SUCCESS] Steam API initialized successfully.
13:40:03.122 INFO steam.SteamIntegration> BUILD ID: 10180494
13:40:03.126 INFO steam.SteamIntegration> CURRENT LANG: english
13:40:03.127 INFO steam.SteamIntegration> ACCOUNT ID: 98584620
13:40:03.127 INFO steam.SteamIntegration> requestGlobalStats
13:40:03.128 INFO steam.SteamTicker> Steam Ticker initialized.
13:40:03.129 INFO core.CardCrawlGame> No migration
13:40:03.133 INFO core.Settings> Initializing display settings...
13:40:03.134 INFO core.DisplayConfig> Reading info.displayconfig
13:40:03.134 INFO core.DisplayConfig> DisplayConfig successfully read.
13:40:03.135 INFO core.Settings> Initializing sound settings...
13:40:03.135 INFO core.Settings> Initializing game settings...
13:40:03.164 INFO localization.LocalizedStrings> Loc Strings load time: 23ms
13:40:03.164 INFO basemod.BaseMod> begin editing localization strings
13:40:03.166 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.RunModStrings
13:40:03.168 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.PowerStrings
13:40:03.168 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.RelicStrings
13:40:03.169 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.UIStrings
13:40:03.169 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.PowerStrings
13:40:03.170 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.RelicStrings
13:40:03.170 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.UIStrings
13:40:03.171 INFO Marisa> <<======================== beginning localization ========================>>
13:40:03.172 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.RelicStrings
13:40:03.173 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.CardStrings
13:40:03.174 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.PowerStrings
13:40:03.174 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.PotionStrings
13:40:03.175 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.EventStrings
13:40:03.175 INFO Marisa> <<======================== finished localization ========================>>
13:40:03.176 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.CardStrings
13:40:03.177 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.CharacterStrings
13:40:03.178 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.RelicStrings
13:40:03.179 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.PowerStrings
13:40:03.179 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.PotionStrings
13:40:03.180 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.UIStrings
13:40:03.191 INFO audio.MusicMaster> Music Volume: 1.0
13:40:03.197 INFO audio.SoundMaster> Sound Effect Volume: 1.0
13:40:03.197 INFO audio.SoundMaster> Loaded 368 Sound Effects
13:40:03.197 INFO audio.SoundMaster> SFX load time: 1ms
13:40:03.197 INFO basemod.BaseMod> begin adding custom sounds
13:40:03.198 INFO basemod.BaseMod> Added 12 sounds
13:40:03.463 INFO steam.SSCallback> 1Bloop: 646570
13:40:04.055 INFO cards.AbstractCard> Card Image load time: 853ms
13:40:04.056 INFO basemod.BaseMod> editting keywords
13:40:04.058 INFO Marisa> <<======================== beginning custom keywords ========================>>
13:40:04.060 INFO Marisa> Loading keyword : 真正的魔法使
13:40:04.061 INFO Marisa> Loading keyword : 才能看到
13:40:04.061 INFO Marisa> Loading keyword : 力竭
13:40:04.061 INFO Marisa> Loading keyword : 火花
13:40:04.061 INFO Marisa> Loading keyword : 蓄力
13:40:04.061 INFO Marisa> Loading keyword : 增幅
13:40:04.061 INFO Marisa> Loading keyword : 黑耀星
13:40:04.062 INFO Marisa> Loading keyword : 白矮星
13:40:04.062 INFO Marisa> Loading keyword : 怨灵
13:40:04.062 INFO Marisa> <<======================== finished custom keywords ========================>>
13:40:04.062 INFO core.CardCrawlGame> Exception occurred in CardCrawlGame create method!
13:40:04.063 ERROR core.CardCrawlGame> Exception caught
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson.Gson.fromJson(Gson.java:826) ~[desktop-1.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:779) ~[desktop-1.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:728) ~[desktop-1.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:700) ~[desktop-1.0.jar:?]
	at ModExample.ModCore.SovietMod.receiveEditKeywords(SovietMod.java:86) ~[SovietMod.jar:?]
	at basemod.BaseMod.publishEditKeywords(BaseMod.java:2681) ~[?:?]
	at basemod.patches.com.megacrit.cardcrawl.helpers.GameDictionary.PostKeywordInitialize.Postfix(PostKeywordInitialize.java:10) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.helpers.GameDictionary.initialize(GameDictionary.java:117) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:276) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350) ~[desktop-1.0.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70) ~[desktop-1.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:814) ~[desktop-1.0.jar:?]
	... 10 more
13:40:04.065 INFO basemod.BaseMod> publishPostInitialize

Exception in thread "LWJGL Application" java.lang.NullPointerException
	at basemod.ModToggleButton.<init>(ModToggleButton.java:42)
	at basemod.ModLabeledToggleButton.<init>(ModLabeledToggleButton.java:29)
	at basemod.ModLabeledToggleButton.<init>(ModLabeledToggleButton.java:23)
	at basemod.BaseModInit.receivePostInitialize(BaseModInit.java:108)
	at basemod.BaseMod.publishPostInitialize(BaseMod.java:2300)
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.PostInitializeHook.Postfix(PostInitializeHook.java:9)
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:307)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by scarf005** [comment]
sorry for the long delay, could you check whether

1. USSR mod without marisa works
2. marisa mod without USSR mod works
3. it only crashes when both mod is used
4. loading soviet mod before marisa mod crashes

thank you for your time.

**Comment by scarf005** [comment]
![image](https://github.com/scarf005/Marisa/assets/54838975/6bcc706c-9210-46ad-83f2-3852fbe76a92)

well, found out it was namespace conflict.
