### ISSUE TITLE
card created from upgraded mysterious beam isn't upgraded

### ISSUE THREAD

**Issue by woshilixinbo** [scarf005/Marisa#213]
### How to reproduce

1. Start a game with Marisa
2. `hand add MysteriousBeam 1 1`
3. use Mysterious Beam.
4. despite the description, card created from  upgraded mysterious beam isn't upgraded.

**Comment by scarf005** [comment]
hello, could you provide more explanation?

1. There's currently no `Mystic Beam` in the mod. did you mean `Mysterious Beam`?
2. Could you explain what does it mean to `strenghten` the card? Do you mean upgrading the card?

**Comment by scarf005** [comment]
the bug is now confirmed.
