### ISSUE TITLE
Acceleration Mechanics Change from basemod - It can now reshuffle your discard pile into your draw pile instead of whiffing with 0 cards in draw. 

### ISSUE THREAD

**Issue by wizzyhatg** [scarf005/Marisa#223]
### How to reproduce

Start a new game
fight lagavulin
Hand Remove all ( 0 in hand, 5 in draw pile, 5 exhausted)
hand add pulsemagic
hand add acceleration
hand add acceleration

Play Pulsemagic, acceleration costs 0, pulsemagic is discarded
Play Acceleration, draw 3 from draw pile
Play Acceleration, two cards are drawn from the top of the draw pile, **then the discard pile is shuffled into the draw pile and another card is drawn**

The wording of Acceleration is "Draw top 2 cards in your draw pile, Amplify 1: Draw 1 more." In the original mod, if you played it with less than 2/3 cards in your draw pile, you would only draw the available cards, and not  shuffle the discard pile into the draw pile. If the draw pile was empty, Acceleration would whiff. In order to 'go infinite' you needed a different draw card to cycle between in order to move your discards to the draw pile

The current implementation appears to simply treat Acceleration as a Draw, which is a much stronger effect.

I took a look at the code for both versions but am not at all familiar with Slay the Spire code. It appears that the [original mod's Acceleration card](https://github.com/lf201014/STS_ThMod_MRS/blob/master/src/main/java/ThMod/cards/Marisa/Acceleration.java) used a custom action [DrawDrawPileAction](https://github.com/lf201014/STS_ThMod_MRS/blob/master/src/main/java/ThMod/action/DrawDrawPileAction.java) which featured 
 `  if (AbstractDungeon.player.drawPile.isEmpty()){
      return;`
so it would whiff if the draw pile was empty, but the [current implementation](https://github.com/scarf005/Marisa/blob/main/src/main/kotlin/marisa/cards/Acceleration.kt) uses DrawCardAction which I think is from the base game?

I apologize for not knowing how to fix this myself but I think that is the crux of the issue?

Thank you for maintaining this mod!!

### Game language

English (ENG)

**Comment by scarf005** [comment]
hello, I made an intentional change (#63) so that it could draw cards infinitely. however, I was unable to update the description across all locales.
