### ISSUE TITLE
one time off not work

### ISSUE THREAD

**Issue by Simuliya** [scarf005/Marisa#238]
### How to reproduce

use one time off
![image](https://github.com/scarf005/Marisa/assets/127732514/357d1647-d26e-495d-8fc9-8297ac82ee61)

use master spark
![image](https://github.com/scarf005/Marisa/assets/127732514/dab71afb-ce1d-4918-97d4-8295c17d5bfb)
use my charge up 8 and  amplify master spark 

### Game language

English (ENG)

**Comment by scarf005** [comment]
hi, sorry for the late reply. this seems to be the intended behavior. regular `One time off` only prevents amplifying. only upgraded `One time off` will also not consume charges.

| `One time off` | `One time off+ (upgraded)` |
| - | - |
| ![image](https://github.com/scarf005/Marisa/assets/54838975/df59e835-0e63-424d-b22f-4acfc82e8451) | ![image](https://github.com/scarf005/Marisa/assets/54838975/818729a3-d394-4028-a3d8-61e7499cd049) |

**Comment by Simuliya** [comment]
![image](https://github.com/scarf005/Marisa/assets/127732514/661b1027-1741-4420-9df7-7e6803019bb2)
sry,but in chinese,regular **One time off** can do it,and origin mod can do it too
