### ISSUE TITLE
Meteoric Shower confuses Burns and other cards

### ISSUE THREAD

**Issue by bluemug97** [scarf005/Marisa#253]
### How to reproduce

1. Start a new game
2. Enter a combat
3. `hand add MeteoricShower`
4. `hand add Burn`
5. Use Meteoric shower to attack an enemy
6. When promted, exhaust Burn
7. Despite card description, Meteoric shower applies 2 instances of damage instead of 3

Conversely:
1. Start a new game
2. Enter a combat
3. `hand add MeteoricShower`
4. Use Meteoric shower to attack an enemy
5. When promted, exhaust any single card
6. Despite card description, Meteoric shower applies 3 instances of damage instead of 2

### Game language

English (ENG)

**Comment by scarf005** [comment]
could you tell which game version are you using?

**Comment by bluemug97** [comment]
Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (12-18-2022)
 - ModTheSpire (3.30.3)
Mod list:
 - basemod (5.54.1)
 - MarisaContinued (4.0.6)

**Comment by bluemug97** [comment]
btw I think I know why this is happening (line 35 in MeteoricShowerAction.kt)
![image](https://github.com/user-attachments/assets/ee4c8946-11b5-45e4-a0d7-e828c83fbcac)
I don't know kotlin well enough to figure out why it's only exhausting burns and not other cards though...

**Comment by scarf005** [comment]
gah, basic mistake. will fix in a mo'.
only burns are exhausted because `withCardsBurned` extension method automatically exhaust burns and i forgot to exhaust regular cards.

**Comment by bluemug97** [comment]
Ahhh I see, thanks for fixing!
